# Unified Nyuchi Platform Worker
name = "nyuchi-platform"
main = "./dist/_worker.js"
compatibility_date = "2024-12-01"

# Enable observability logs
[observability.logs]
enabled = true

# Production environment
[env.production]
name = "nyuchi-platform-prod"
routes = [
  "www.nyuchi.com/*",
  "nyuchi.com/*"
]
zone_id = "049bd85976a3767c9bfa4aaee38fc937"

# Preview environment
[env.preview]
name = "nyuchi-platform-preview"
routes = [
  "preview.nyuchi.com/*"
]
zone_id = "049bd85976a3767c9bfa4aaee38fc937"

# Environment variables
[vars]
NODE_ENV = "production"
ASTRO_BUILD = "true"

# KV storage for session data
[[kv_namespaces]]
binding = "SESSIONS"
id = "session_kv_id"
preview_id = "session_kv_preview_id"

# D1 database
[[d1_databases]]
binding = "DB"
database_name = "nyuchi-db"
database_id = "database_id_here"

# R2 bucket for file storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "nyuchi-storage"
preview_bucket_name = "nyuchi-storage-preview"
