# Nyuchi Dashboard Worker - Backend/Admin Platform
name = "nyuchi-dashboard"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# Local development variables
[vars]
ENVIRONMENT = "development"
NODE_ENV = "development"
SUPABASE_URL = "https://zylxjonmgjvqursoxdde.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bHhqb25tZ2p2cXVyc294ZGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDk2MTgsImV4cCI6MjA3MTE4NTYxOH0.LZDuNNKUhL_yLB2T9Ln0T2VBjogzx3XQz8-lbuFIl8A"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bHhqb25tZ2p2cXVyc294ZGRlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTYwOTYxOCwiZXhwIjoyMDcxMTg1NjE4fQ.jeEUyA8y97KkuOcuutQAVkF0erDyGF_llrt5bwIlrfI"
ANALYTICS_ENABLED = "false"

# D1 Database for development
[[d1_databases]]
binding = "DB"
database_name = "nyuchi-dashboard-db"
database_id = "create_with_wrangler_d1_create"

# KV Namespaces for development
[[kv_namespaces]]
binding = "SESSION"
id = "55dc82737fd8427ebc6a8e6d405c043f"

[[kv_namespaces]]
binding = "CACHE"
id = "6541da165e384d2fbe8530ecb98f6b79"

# R2 Storage for development
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "nyuchi-storage"

# Production Environment
[env.production]
name = "nyuchi-dashboard-prod"
zone_id = "049bd85976a3767c9bfa4aaee38fc937"
routes = [
  { pattern = "dashboard.nyuchi.com/*", zone_id = "049bd85976a3767c9bfa4aaee38fc937" },
  { pattern = "admin.nyuchi.com/*", zone_id = "049bd85976a3767c9bfa4aaee38fc937" }
]

[env.production.vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
ASTRO_BUILD = "true"
SUPABASE_URL = "https://zylxjonmgjvqursoxdde.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bHhqb25tZ2p2cXVyc294ZGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDk2MTgsImV4cCI6MjA3MTE4NTYxOH0.LZDuNNKUhL_yLB2T9Ln0T2VBjogzx3XQz8-lbuFIl8A"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bHhqb25tZ2p2cXVyc294ZGRlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTYwOTYxOCwiZXhwIjoyMDcxMTg1NjE4fQ.jeEUyA8y97KkuOcuutQAVkF0erDyGF_llrt5bwIlrfI"
ANALYTICS_ENABLED = "true"

# Same resources for production
[[env.production.kv_namespaces]]
binding = "SESSION"
id = "55dc82737fd8427ebc6a8e6d405c043f"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "6541da165e384d2fbe8530ecb98f6b79"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "nyuchi-storage"